language: clojure
lein: lein2
script: lein2 test

notifications:
   email: false
   irc: 
      channels: 
         - "chat.freenode.net#mochify"
      use_notice: true
      skip_join: true
      template:
         - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
         - "Commit view : %{compare_url}"
