language: clojure
lein: lein2
script: lein2 with-profile compile test

jdk:
    - openjdk6
    - openjdk7
    - oraclejdk7

notifications:
   email: false
   irc: 
      channels: 
         - "chat.freenode.net#mochify"
      use_notice: true
      skip_join: true
      template:
         - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
         - "Commit view : %{compare_url}"
